# Generated by Django 5.2.8 on 2025-12-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_district_user_current_carbon_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='latitude',
            field=models.FloatField(default=43.238949),
        ),
        migrations.AddField(
            model_name='district',
            name='longitude',
            field=models.FloatField(default=76.889709),
        ),
    ]
